[package]
name = "rendering"
version = "0.1.0"
authors = ["Marko Sego <ms50303@fer.hr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
ggez = "0.5"